name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y  clang-19 libclang-19-dev libclang-common-19-dev libclang-cpp19 libclang-cpp19-dev libc++-19-dev libsdl2-2.0-0 libsdl2-dev catch2 valgrind
    
    - name: configure
      run: rm -Rf build ; cmake -B build
    - name: make
      run: cmake --build build
    - name: Test 1
      run: valgrind --leak-check=full -s ./build/bin/tests
    - name: Test 2
      run: valgrind ./build/bin/engineOnly

