name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang-19 libclang-19-dev libclang-common-19-dev libclang-cpp19 libclang-cpp19-dev libsdl2-2.0-0 libsdl2-dev libc++-19-dev
    
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: Test
      run: ./build/bin/tests && ./build/bin/engineOnly

