name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: llvmclang/clang:latest  # Clang preinstalled

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libsdl2-2.0-0 libsdl2-dev catch2
    
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: Test
      run: ./build/bin/tests && ./build/bin/engineOnly

